### PR TITLE
Proposal:

### PR DESCRIPTION
**Pull request by kvrzh**
Add axios-retry to axios to allow retry axios requests easy

### CODE REVIEW

**Comment by tanishqmanuja** [comment]
Thanks for the PR, but due to single responsibility principle this library itself cannot have retry. Although the internal axios instance is exposed to the users for modification.

You can do something like this https://github.com/tanishqmanuja/valorant-api-client/blob/legacy/examples/vapic-local-advance.ts

Here's another snippet from my unpublished project
```ts
import {
  createRateLimitInterceptor,
  createRetryInterceptor,
  createAuthRefreshInterceptor,
  createCacheInterceptor,
} from "@tqman/axios-interceptor-suite";
import {
  ValorantApiClient,
  provideAuthViaLocalApi,
  getAccessTokenHeader,
  getEntitlementsJWTHeader,
} from "@tqman/valorant-api-client";
import type { AxiosError } from "axios";
import { getApiLogger } from "~/logger";
import { createLoggerInterceptor } from "./interceptor";

async function refreshTokens(api: ValorantApiClient, error: AxiosError) {
  const authProvider = provideAuthViaLocalApi();

  const { accessToken, entitlementsToken } = await authProvider(api);

  const authHeaders = {
    ...getAccessTokenHeader(accessToken),
    ...getEntitlementsJWTHeader(entitlementsToken),
  };

  // Set for whole instance
  api.remote.reinitialize({
    ...api.remote.options,
    accessToken,
    entitlementsToken,
  });

  // Set for this request
  if (error.response) {
    error.response.config.headers = Object.assign(
      error.response.config.headers,
      authHeaders,
    );

    Promise.resolve(error);
  }

  Promise.reject(error);
}

export function modifyApiBehaviour(api: ValorantApiClient) {
  const localAxiosInstance = api.local.axiosInstance;
  const remoteAxiosInstance = api.remote.axiosInstance;

  createRateLimitInterceptor(localAxiosInstance, {
    count: 10,
    interval: 1 * 1000,
  });

  createRateLimitInterceptor(remoteAxiosInstance, {
    count: 6,
    interval: 1 * 1000,
  });

  createCacheInterceptor(localAxiosInstance);
  createCacheInterceptor(remoteAxiosInstance);

  createAuthRefreshInterceptor(remoteAxiosInstance, {
    statusCodes: [400],
    onRefresh: error => refreshTokens(api, error),
  });

  createRetryInterceptor(remoteAxiosInstance, {
    count: 2,
    delay: 1 * 1000,
    condition: error =>
      error.code !== "ECONNABORTED" &&
      (!error.response ||
        (error.response.status >= 500 && error.response.status <= 599)),
  });

  const logger = getApiLogger();
  createLoggerInterceptor(remoteAxiosInstance, {
    info: (msg: string) => logger.info(msg),
    error: (msg: string) => logger.error(msg),
  });
}

```

**Comment by kvrzh** [comment]
Thanks, didn't know what it's possible to get axiosInstance

**Comment by tanishqmanuja** [comment]
Not your fault. Actually documentation is pretty basic, and examples are not present. I will update them for sure in the future 🙂

**Comment by tanishqmanuja** [comment]
added to docs: 81fdd1d74d439e72aa3055d6b03ac54b7e628f7e

**Pull request closed without merging**
